steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/admin-git:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/admin-git:latest'
      - '.'
    id: 'build-image'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/${PROJECT_ID}/admin-git'
    id: 'push-image'
    waitFor: ['build-image']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'admin-git'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/admin-git:$COMMIT_SHA'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
    id: 'deploy-cloud-run'
    waitFor: ['push-image']

# Build timeout
timeout: '1200s'

# Build options - required when service account is specified
options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

# Images to be pushed to Container Registry (automatic push)
images:
  - 'gcr.io/${PROJECT_ID}/admin-git:$COMMIT_SHA'
  - 'gcr.io/${PROJECT_ID}/admin-git:latest'

